"""
Dream Curriculum - Autonomous Fine-Tuning Dataset Generation.

Part of Phase 29: Advanced Self-Optimization.
This module takes raw 'Dreams' (creative memory recombinations) and 'Wisdom' 
(high-confidence insights) generated during sleep or reflection, and distills 
them into structured fine-tuning examples (e.g. JSONL formats for LoRA).
This allows Manas to 'compress' slow, deliberative reasoning into fast, 
instinctual reflexes.
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any

logger = logging.getLogger(__name__)

class CurriculumGenerator:
    """
    Distills deep reasoning and dreams into structured SFT (Supervised Fine-Tuning) 
    datasets to bake knowledge into the base model weights over time.
    """
    def __init__(self, llm_router, data_dir: str):
        self.llm_router = llm_router
        self.data_dir = Path(data_dir)
        self.curriculum_dir = self.data_dir / "curriculum"
        self.curriculum_dir.mkdir(parents=True, exist_ok=True)
        self.current_dataset = self.curriculum_dir / "dream_dataset.jsonl"
        self.total_examples_generated = 0
        
    def generate_from_dream(self, dream_data: Dict[str, Any]) -> Optional[Dict[str, str]]:
        """
        Takes a complex dream narrative and asks the LLM to format it into a Q&A pair.
        """
        narrative = dream_data.get("dream", "")
        if not narrative or len(narrative) < 50:
            return None
            
        prompt = (
            f"As Manas's Curriculum Generator, distill this 'dream' (a creative recombination of memories) "
            f"into a structured instruction-response pair for fine-tuning.\n\n"
            f"DREAM:\n{narrative}\n\n"
            f"Create a hypothetical User User/Question that this dream elegantly answers, "
            f"and formulate the Response as a wise, concise insight.\n"
            f"Output ONLY valid JSON in format: {{\"instruction\": \"...\", \"response\": \"...\"}}"
        )
        
        try:
            res = self.llm_router.generate(prompt=prompt, task_type="reasoning")
            # clean JSON
            res = res.replace("```json", "").replace("```", "").strip()
            pair = json.loads(res)
            
            if "instruction" in pair and "response" in pair:
                self._append_to_dataset(pair)
                return pair
            return None
        except Exception as e:
            logger.debug(f"Failed to generate curriculum from dream: {e}")
            return None

    def generate_from_wisdom(self, wisdom_data: Dict[str, Any]) -> Optional[Dict[str, str]]:
        """
        Takes high-confidence Wisdom generated by the Reflection or Reasoning engines
        and turns it into a high-quality SFT example.
        """
        topic = wisdom_data.get("topic", "")
        insight = wisdom_data.get("insight", "")
        
        prompt = (
            f"Convert the following profound system insight into a high-quality "
            f"training example for a language model.\n\n"
            f"TOPIC: {topic}\n"
            f"INSIGHT: {insight}\n\n"
            f"Format as an instruction-response pair where the model demonstrates this insight.\n"
            f"Output ONLY valid JSON in format: {{\"instruction\": \"...\", \"response\": \"...\"}}"
        )
        
        try:
            res = self.llm_router.generate(prompt=prompt, task_type="reasoning")
            res = res.replace("```json", "").replace("```", "").strip()
            pair = json.loads(res)
            
            if "instruction" in pair and "response" in pair:
                self._append_to_dataset(pair)
                return pair
            return None
        except Exception as e:
            logger.debug(f"Failed to generate curriculum from wisdom: {e}")
            return None
            
    def _append_to_dataset(self, example: Dict[str, str]):
        """Appends a valid instruction/response pair to the JSONL dataset."""
        try:
            with open(self.current_dataset, "a") as f:
                f.write(json.dumps(example) + "\n")
            self.total_examples_generated += 1
        except Exception as e:
            logger.error(f"CurriculumGenerator failed to write dataset: {e}")
            
    def get_status(self) -> str:
        return (
            f"📚 Curriculum Generator:\n"
            f"  Dataset path: {self.current_dataset}\n"
            f"  Examples generated: {self.total_examples_generated}"
        )
