from .amygdala import Amygdala
from .prefrontal import PrefrontalCortex
from .hippocampus import Hippocampus
from .sensory import SensoryProcessor
from .thalamus import Thalamus
from .basal_ganglia import BasalGanglia
from .cerebellum import Cerebellum
from .insula import Insula
from .acc import ACC
