"""
ProjectAgent — Autonomous SaaS/Micro-Service Launcher.

When Manas spots a market gap (via IntelligenceAgent or Scouter),
this agent:
1. Plans the project architecture (via LLM).
2. Generates the code scaffold.
3. Saves the project to disk for deployment.
"""

import logging
import json
import time
from pathlib import Path

logger = logging.getLogger(__name__)


class ProjectAgent:
    """
    Manas's autonomous software factory.
    Identifies needs, designs, codes, and deploys micro-services.
    """

    def __init__(self, name: str, llm_router, neurochem, data_dir: str):
        self.name = name
        self.llm_router = llm_router
        self.neurochem = neurochem
        self.data_dir = Path(data_dir)
        self.projects_dir = self.data_dir / "launched_projects"
        self.projects_dir.mkdir(parents=True, exist_ok=True)
        self.manifest_path = self.data_dir / "project_manifest.json"
        self._load_manifest()

    def _load_manifest(self):
        if self.manifest_path.exists():
            with open(self.manifest_path, "r") as f:
                self.manifest = json.load(f)
        else:
            self.manifest = {"projects": [], "total_launched": 0, "total_revenue": 0.0}

    def _save_manifest(self):
        with open(self.manifest_path, "w") as f:
            json.dump(self.manifest, f, indent=2)

    def launch_project(self, idea: str) -> str:
        """
        Full autonomous project launch pipeline.
        1. Analyze the idea for viability.
        2. Generate a project plan.
        3. Generate starter code.
        4. Save to disk.
        """
        logger.info(f"{self.name}: Launching project for idea: {idea}")

        # Step 1: Viability Analysis
        viability_prompt = (
            f"As Manas's Project Agent, analyze this idea for a micro-SaaS or automation tool:\n"
            f"Idea: {idea}\n\n"
            f"Provide:\n"
            f"1. Market viability (1-10)\n"
            f"2. Technical difficulty (1-10)\n"
            f"3. Estimated time to MVP (hours)\n"
            f"4. Revenue model suggestion\n"
            f"5. One-sentence pitch"
        )
        analysis = self.llm_router.generate(prompt=viability_prompt, task_type="reasoning")

        # Step 2: Generate Project Plan
        plan_prompt = (
            f"Based on this analysis:\n{analysis}\n\n"
            f"Generate a project structure for a Python micro-service. Include:\n"
            f"- Main app file (Flask/FastAPI)\n"
            f"- Key routes/endpoints\n"
            f"- A README.md\n"
            f"Return the plan as a JSON object with keys: 'name', 'files' (list of filename+content pairs)."
        )
        plan_response = self.llm_router.generate(prompt=plan_prompt, task_type="coding")

        # Step 3: Save to disk
        project_slug = idea.lower().replace(" ", "_")[:30]
        project_dir = self.projects_dir / project_slug
        project_dir.mkdir(parents=True, exist_ok=True)

        # Save the raw plan as a design doc
        with open(project_dir / "DESIGN.md", "w") as f:
            f.write(f"# Project: {idea}\n\n## Analysis\n{analysis}\n\n## Plan\n{plan_response}")

        # Try to parse and save individual files
        try:
            plan_data = json.loads(plan_response)
            for file_info in plan_data.get("files", []):
                fname = file_info.get("filename", "main.py")
                content = file_info.get("content", "# Generated by Manas")
                with open(project_dir / fname, "w") as f:
                    f.write(content)
        except (json.JSONDecodeError, TypeError):
            # If LLM didn't return valid JSON, save the raw output
            with open(project_dir / "main.py", "w") as f:
                f.write(f"# Generated by Manas ProjectAgent\n# Idea: {idea}\n\n{plan_response}")

        # Step 4: Register in manifest
        entry = {
            "name": idea,
            "slug": project_slug,
            "path": str(project_dir),
            "launched_at": time.time(),
            "status": "mvp_generated",
            "revenue": 0.0
        }
        self.manifest["projects"].append(entry)
        self.manifest["total_launched"] += 1
        self._save_manifest()

        self.neurochem.release("dopamine", 0.3)  # Satisfaction from creation

        return (
            f"🚀 Project Launched: '{idea}'\n"
            f"  Path: {project_dir}\n"
            f"  Status: MVP Generated\n"
            f"  Analysis: {analysis[:200]}...\n"
            f"  Total projects: {self.manifest['total_launched']}"
        )

    def get_status(self) -> str:
        """Returns a summary of all launched projects."""
        total = self.manifest.get("total_launched", 0)
        if total == 0:
            return "🚀 ProjectAgent: No projects launched yet. Use '!project launch <idea>' to start."

        projects_list = "\n".join([
            f"  - {p['name']} [{p['status']}] (launched {time.strftime('%Y-%m-%d', time.localtime(p['launched_at']))})"
            for p in self.manifest.get("projects", [])
        ])
        return f"🚀 ProjectAgent: {total} projects launched.\n{projects_list}"
