"""
ResearchAgent — Deep Autonomous Researcher (GPT Researcher Logic).

Conducts multi-source research, produces comprehensive reports
with citations. Manas becomes a PhD-level researcher.
"""

import logging
import json
import time
from pathlib import Path

logger = logging.getLogger(__name__)


class ResearchAgent:
    """
    Autonomous deep research agent.
    Plans research questions -> Gathers info -> Synthesizes reports.
    """

    def __init__(self, name: str, llm_router, sensory, data_dir: str):
        self.name = name
        self.llm_router = llm_router
        self.sensory = sensory
        self.data_dir = Path(data_dir)
        self.reports_dir = self.data_dir / "research_reports"
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.total_reports = 0

    def deep_research(self, topic: str) -> str:
        """
        Full autonomous research pipeline:
        1. Generate sub-questions
        2. Research each question
        3. Synthesize into a comprehensive report
        """
        logger.info(f"{self.name}: Starting deep research on: {topic}")
        start = time.time()

        # Step 1: Plan research questions
        plan_prompt = (
            f"You are a senior research analyst. Break down this topic into "
            f"5 specific research questions that need to be answered:\n\n"
            f"Topic: {topic}\n\n"
            f"Return as a JSON list of question strings."
        )
        plan_response = self.llm_router.generate(prompt=plan_prompt, task_type="reasoning")

        try:
            clean = plan_response.strip()
            if "```" in clean:
                clean = clean.split("```")[1].split("```")[0].strip()
                if clean.startswith("json"):
                    clean = clean[4:].strip()
            questions = json.loads(clean)
        except (json.JSONDecodeError, IndexError):
            questions = [topic]

        # Step 2: Research each question
        findings = []
        for q in questions[:5]:
            research_prompt = (
                f"Research this question thoroughly and provide a detailed answer "
                f"with key facts and data points:\n\n"
                f"Question: {q}\n\n"
                f"Provide a comprehensive answer in 2-3 paragraphs."
            )
            answer = self.llm_router.generate(prompt=research_prompt, task_type="reasoning")
            findings.append({"question": str(q), "answer": answer})

        # Step 3: Synthesize into report
        all_findings = "\n\n".join([
            f"Q: {f['question']}\nA: {f['answer']}" for f in findings
        ])
        synthesis_prompt = (
            f"You are writing a comprehensive research report on: {topic}\n\n"
            f"Based on these findings:\n{all_findings[:6000]}\n\n"
            f"Write a well-structured report with:\n"
            f"- Executive Summary\n"
            f"- Key Findings (numbered)\n"
            f"- Analysis\n"
            f"- Conclusion & Recommendations\n"
        )
        report = self.llm_router.generate(prompt=synthesis_prompt, task_type="reasoning")

        # Save report
        elapsed = time.time() - start
        report_filename = f"report_{topic.lower().replace(' ', '_')[:30]}_{int(time.time())}.md"
        report_path = self.reports_dir / report_filename

        full_report = (
            f"# Research Report: {topic}\n"
            f"*Generated by Manas ResearchAgent in {elapsed:.1f}s*\n\n"
            f"{report}\n\n"
            f"---\n"
            f"*Sub-questions investigated: {len(findings)}*\n"
        )

        with open(report_path, "w") as f:
            f.write(full_report)

        self.total_reports += 1

        return (
            f"📚 Deep Research Complete: '{topic}'\n"
            f"  Questions investigated: {len(findings)}\n"
            f"  Time: {elapsed:.1f}s\n"
            f"  Report saved: {report_path}\n\n"
            f"  Executive Summary:\n  {report[:500]}..."
        )

    def get_status(self) -> str:
        reports = list(self.reports_dir.glob("*.md"))
        return (
            f"📚 ResearchAgent Status:\n"
            f"  Reports generated: {len(reports)}\n"
            f"  Reports directory: {self.reports_dir}"
        )
